apiVersion: v1
kind: Service
metadata:
  name: pixora-backend-service
  namespace: default
spec:
  selector:
    app: pixora-backend          # deployment ile eşleşir
  ports:
    - protocol: TCP
      port: 80                   # dışarıya açılan port
      targetPort: 8000           # container'ın portu
  type: ClusterIP                # sadece cluster içinden erişilir